# Generated by Django 3.2.25 on 2024-06-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=3000)),
                ('image_url', models.URLField(max_length=400)),
                ('discount', models.CharField(max_length=4)),
                ('link', models.URLField(max_length=1200)),
            ],
            options={
                'verbose_name': 'OZON товар',
                'verbose_name_plural': "Товары OZON'a",
            },
        ),
    ]
